lane :apply do
  patch files: "examples/PatchTestAndroid/app/src/main/AndroidManifest.xml",
        patch: "patch.yaml"
end

lane :revert do
  patch files: "examples/PatchTestAndroid/app/src/main/AndroidManifest.xml",
        patch: "patch.yaml",
        revert: true
end
